export const ENTRIES = [
    { "user_id": "1", "mood": "Low", "energy": 1, "note": "Terrible sleep last night, had back to back meetings all day and skipped lunch. Felt completely drained by 2pm. The project deadline pressure is getting to me.", "score": 1.0, "created_at": "2026-04-21 08:23:00" },
    { "user_id": "1", "mood": "Meh", "energy": 2, "note": "Still tired from yesterday. Meetings again in the morning. Managed to get some code done in the afternoon but nothing felt satisfying. Ate poorly today.", "score": 3.5, "created_at": "2026-04-22 09:10:00" },
    { "user_id": "1", "mood": "Good", "energy": 4, "note": "No meetings today which made a huge difference. Deep work session in the morning, finished the dashboard layout. Had a proper meal and went for a short walk. Feeling more like myself.", "score": 6.5, "created_at": "2026-04-23 10:05:00" },
    { "user_id": "1", "mood": "Great", "energy": 4, "note": "Another meeting-free day. Woke up early, worked out before sitting down. Fixed the routing bug that has been bothering me all week. Had lunch with a friend which lifted my mood a lot.", "score": 8.5, "created_at": "2026-04-24 08:50:00" },
    { "user_id": "1", "mood": "Amazing", "energy": 5, "note": "Best day this week. Slept 8 hours, worked out, ate well. Everything clicked — fixed the auth bug, deployed to staging, got great feedback. Music on, full flow state for 4 hours straight.", "score": 10.0, "created_at": "2026-04-25 09:30:00" },
    { "user_id": "1", "mood": "Good", "energy": 3, "note": "Relaxed Saturday. No work, just rested and watched tutorials. Cooked my own food and called my family. Low energy but genuinely happy.", "score": 6.0, "created_at": "2026-04-26 11:00:00" },
    { "user_id": "1", "mood": "Meh", "energy": 2, "note": "Sunday anxiety kicking in. Thinking about the week ahead and all the tasks piling up. Scrolled too much, barely left the house. Skipped the gym again.", "score": 3.5, "created_at": "2026-04-27 14:20:00" },
    { "user_id": "1", "mood": "Good", "energy": 3, "note": "Decent Monday surprisingly. Planned out the week properly before starting. Avoided unnecessary meetings. Had coffee and music going — solid 5 hour focus block.", "score": 6.0, "created_at": "2026-04-28 08:45:00" },
    { "user_id": "1", "mood": "Great", "energy": 5, "note": "Woke up naturally before the alarm. Gym in the morning, cold shower after. No meetings, deep work all day. Finished the entry store, fixed the foreign key bug. Felt unstoppable.", "score": 9.0, "created_at": "2026-04-29 09:15:00" },
    { "user_id": "1", "mood": "Good", "energy": 4, "note": "Good end to the month. Reviewed everything built so far and felt proud. Had one short meeting that was actually useful. Cooked dinner, journaled a bit, slept early.", "score": 6.5, "created_at": "2026-04-30 10:30:00" }
]